<?php
    return [
        'typeMotorcycles' => [
            'Motorbikes for Sale',
            'Motorbikes for Sale > 2',
            'Motorbikes for Sale > 2A',
            'Motorbikes for Sale > 2B',
            'Motorbike Rental',
            'Motorbike Apparel',
            'Motorbike Accessories',
            'Any',
        ],
        'motorTopicNames' => [
            'Motorcycles for Sale',
            'Motorcycles Rental',
            'Motorcycles Apparel',
            'Motorcycles Accessories',
        ],
        'motorTopics' => [
            'https://sl3-cdn.karousell.com/homescreens/motorbikes_133/motorbike-for-sale.svg',
            'https://sl3-cdn.karousell.com/homescreens/motorbikes_133/motorbike-rental.svg',
            'https://sl3-cdn.karousell.com/homescreens/motorbikes_133/motorbike-apparel.svg',
            'https://sl3-cdn.karousell.com/homescreens/motorbikes_133/motorbike-accessories.svg',
        ],

        'motorBrands' => [
            'https://sl3-cdn.karousell.com/homescreens/motorbikes_133/make-yamaha.svg',
            'https://sl3-cdn.karousell.com/homescreens/motorbikes_133/make-vespa.svg',
            'https://sl3-cdn.karousell.com/homescreens/motorbikes_133/make-kawasaki.svg',
            'https://sl3-cdn.karousell.com/homescreens/cars_22/make_honda_rebranding_newcarhs@2x.png',
            'https://sl3-cdn.karousell.com/homescreens/cars_22/make_suzuki_rebranding_newcarhs@2x.png',
            'https://sl3-cdn.karousell.com/homescreens/motorbikes_133/make-harley.svg',
            'https://sl3-cdn.karousell.com/homescreens/motorbikes_133/make-ktm.svg',
            'https://sl3-cdn.karousell.com/homescreens/motorbikes_133/make-ducati.svg',
            'https://sl3-cdn.karousell.com/homescreens/cars_22/make_bmw_rebranding_newcarhs@2x.png',
            'https://sl3-cdn.karousell.com/homescreens/motorbikes_133/make-gilera.svg',
            'https://sl3-cdn.karousell.com/homescreens/motorbikes_133/make-agv.svg',
            'https://sl3-cdn.karousell.com/homescreens/motorbikes_133/make-shoei.svg',
            'https://sl3-cdn.karousell.com/homescreens/motorbikes_133/make-arai.svg',
        ],
        'motorBrandNames' => [
            'Yamaha',
            'Vespa',
            'Kawasaki',
            'Honda',
            'Suzuki',
            'Harley',
            'KTM',
            'Ducati',
            'BMW',
            'Gilera',
            'AGV',
            'Shoei',
            'Arai'
        ],

        'motors' => [
            'https://media.karousell.com/media/photos/products/2022/10/10/yamaha_fjr_1300_2013_gen_3_1665387214_092d833f_progressive_thumbnail',
            'https://media.karousell.com/media/photos/products/2022/2/15/yamaha_xsr155_agent_bike_1644919582_f4f22e98_progressive_thumbnail',
            'https://media.karousell.com/media/photos/products/2022/11/9/arai_ram_4_mimetic_1667980949_81d9e65d_progressive_thumbnail.jpg',
            'https://media.karousell.com/media/photos/products/2022/11/9/_jan_2022_aerox155__aerox_155__1667980901_371d8d1d_progressive_thumbnail',
            'https://media.karousell.com/media/photos/products/2022/11/9/sena_3s_plus_universal_bluetoo_1667980854_c0ccc82d_progressive_thumbnail.jpg',
            'https://media.karousell.com/media/photos/products/2022/5/24/adv150_storage_padding_leather_1653381750_b661b65e_progressive_thumbnail.jpg',
            'https://media.karousell.com/media/photos/products/2021/7/23/bike_rental_1627014147_1cf2a771_progressive_thumbnail.jpg',
            'https://media.karousell.com/media/photos/products/2021/9/21/brand_new_honda_cb350_hness_1632208901_10a2fbc8_progressive_thumbnail.jpg',
            'https://media.karousell.com/media/photos/products/2022/11/6/harley_davidson_tourer_saddle__1667724292_3b1fc0eb_progressive_thumbnail.jpg',
            'https://media.karousell.com/media/photos/products/2022/9/3/yamaha_r15v2_for_rental_1662198467_25167392_progressive_thumbnail.jpg',
            'https://media.karousell.com/media/photos/products/2022/11/9/_tricity_155__tricity155__tric_1667980543_f245b636_progressive_thumbnail',
            'https://media.karousell.com/media/photos/products/2022/11/9/yoshimura_roundcone_1667980418_9ea7b66b_progressive_thumbnail.jpg',
            'https://media.karousell.com/media/photos/products/2022/9/22/cb190x_honda_tourism_1663855977_15dc013f_progressive_thumbnail.jpg',
            'https://media.karousell.com/media/photos/products/2022/11/9/sniper_155_uptank_7liter_1667980234_741cb930_progressive_thumbnail.jpg',
            'https://media.karousell.com/media/photos/products/2022/10/21/sym_gts_200_1666344068_437f717c_progressive_thumbnail.jpg',
        ]
    ];
