<?php
return [
    'headerSearch' => [
        'Used Cars',
        'Car Rental',
        'Parallel Imports',
        'Commercial Vehicles',
        'Car Accessories',
        'Motorcycles'
    ],
    'headerLinks' => [
      '/used-car',
      '/rental-car',
      '/parallel',
      '/commercial-vehicle',
      '/accessories-car',
      '/motorcycles',
    ],

    'body' => [
        'Sedan',
        'Hatchback',
        'SUV',
        'MPV',
        'Coupe',
        'Cabriolet',
        'Station Wagon',
    ],

    'depreciation' => [
        '<7k',
        '<8k',
        '<9k',
        '<10k',
        '10k - 11k',
        '11k - 12k',
        '12k - 13k',
        '13k - 14k',
        '14k - 16k',
        '16k - 18k',
        '18k - 20k',
        '>20k',
        'Any'
    ],

    'trending' => [
        'Volkswagen Scirocco',
        'Honda Civic',
        'Audi A3',
        'Toyota Vios',
        'Nissan GTR',
        'Subaru Impreza',
        'MINI cooper',
        'Suzuki Swift',
        'Mitsubishi Lancer',
        'Kia Cerato Forte',
        'Mazda 3',
    ],

    'topic' => [
        'https://sl3-cdn.karousell.com/homescreens/main/sg_web_homepage/cars/carrental.png',
        'https://sl3-cdn.karousell.com/homescreens/main/sg_web_homepage/cars/parallelimports.png',
        'https://sl3-cdn.karousell.com/homescreens/main/sg_web_homepage/cars/commercialvehicles.png',
        'https://sl3-cdn.karousell.com/homescreens/main/sg_web_homepage/cars/caraccessories.png',
        'https://sl3-cdn.karousell.com/homescreens/main/sg_web_homepage/cars/motorcycles.png',
    ],
    'topicNames' => [
        'Car Rental',
        'Parallel Import',
        'Commercial Vehicles',
        'Car Accessories',
        'Motorcycles',
    ],

    'popularBrandNames' => [
        'BMW',
        'Honda',
        'Volkswagen',
        'Mercedes Benz',
        'Audi',
        'Toyota',
        'Porsche',
        'Subaru',
        'MINI',
        'Suzuki',
        'Mitsubishi',
        'Lexus',
        'Kia',
        'Mazda',
        'Hyundai',
        'Skoda',
        'Jeep',
        'Land Rover',
        'Nissan',
        'Volvo',
        'Ssangyong',
        'Chevrolet',
    ],
    'popularBrands' => [
        'https://sl3-cdn.karousell.com/homescreens/cars_22/make_bmw_rebranding_newcarhs@2x.png',
        'https://sl3-cdn.karousell.com/homescreens/cars_22/make_honda_rebranding_newcarhs@2x.png',
        'https://sl3-cdn.karousell.com/homescreens/cars_22/make_volkswagen_rebranding_newcarhs@2x.png',
        'https://sl3-cdn.karousell.com/homescreens/cars_22/make_mercedes_rebranding_newcarhs@2x.png',
        'https://sl3-cdn.karousell.com/homescreens/cars_22/make_audi_rebranding_newcarhs@2x.png',
        'https://sl3-cdn.karousell.com/homescreens/cars_22/make_toyota_rebranding_newcarhs@2x.png',
        'https://sl3-cdn.karousell.com/homescreens/cars_22/make_porsche_rebranding_newcarhs@2x.png',
        'https://sl3-cdn.karousell.com/homescreens/cars_22/make_subaru_rebranding_newcarhs@2x.png',
        'https://sl3-cdn.karousell.com/homescreens/cars_22/make_mini_rebranding_newcarhs@2x.png',
        'https://sl3-cdn.karousell.com/homescreens/cars_22/make_suzuki_rebranding_newcarhs@2x.png',
        'https://sl3-cdn.karousell.com/homescreens/cars_22/make_mitsubishi_rebranding_newcarhs@2x.png',
        'https://sl3-cdn.karousell.com/homescreens/cars_22/make_lexus_rebranding_newcarhs@2x.png',
        'https://sl3-cdn.karousell.com/homescreens/cars_22/make_kia_v2@2x.png',
        'https://sl3-cdn.karousell.com/homescreens/cars_22/make_mazda_rebranding_newcarhs@2x.png',
        'https://sl3-cdn.karousell.com/homescreens/cars_22/make_hyundai_rebranding_newcarhs@2x.png',
        'https://sl3-cdn.karousell.com/homescreens/cars_22/make_skoda_rebranding_newcarhs@2x.png',
        'https://sl3-cdn.karousell.com/homescreens/cars_22/make_jeep_rebranding_newcarhs@2x.png',
        'https://sl3-cdn.karousell.com/homescreens/cars_22/make_land_rover_rebranding_newcarhs@2x.png',
        'https://sl3-cdn.karousell.com/homescreens/cars_22/make_nissan_rebranding_newcarhs@2x.png',
        'https://sl3-cdn.karousell.com/homescreens/cars_22/make_volvo_rebranding_newcarhs@2x.png',
        'https://sl3-cdn.karousell.com/homescreens/cars_22/make_ssangyong_rebranding_newcarhs@2x.png',
        'https://sl3-cdn.karousell.com/homescreens/cars_22/make_chevrolet_rebranding_newcarhs@2x.png',
    ],

    'cars' => [
        'car1' => [
            'https://media.karousell.com/media/photos/products/2022/11/4/toyota_sienta_15_x_7seater_a_1667545331_07a4ed24_progressive.jpg',
            'https://media.karousell.com/media/photos/products/2022/11/4/toyota_sienta_15_x_7seater_a_1667545331_ce7936b6_progressive.jpg',
            'https://media.karousell.com/media/photos/products/2022/11/4/toyota_sienta_15_x_7seater_a_1667545331_f8158897_progressive.jpg',
        ],
        'car2' => [
            'https://media.karousell.com/media/photos/products/2022/9/17/toyota_hiace_diesel_28a_euro_6_1663399773_b826ee2f_progressive_thumbnail.jpg',
            'https://media.karousell.com/media/photos/products/2022/9/29/toyota_hiace_diesel_28a_euro_6_1664420315_f51e863a_progressive.jpg',
            'https://media.karousell.com/media/photos/products/2022/9/29/toyota_hiace_diesel_28a_euro_6_1664420315_88b5d9e3_progressive.jpg',
        ],
        'car3' => [
            'https://media.karousell.com/media/photos/products/2022/8/25/honda_jade_15_rs_vtec_turbo_a_1661415713_25c86796_progressive.jpg',
            'https://media.karousell.com/media/photos/products/2022/8/25/honda_jade_15_rs_vtec_turbo_a_1661415713_52922fad_progressive_thumbnail.jpg',
            'https://media.karousell.com/media/photos/products/2022/8/25/honda_jade_15_rs_vtec_turbo_a_1661415713_c3440f9e_progressive.jpg',
        ],
        'car4' => [
            'https://media.karousell.com/media/photos/products/2022/11/1/bmw_2_series_convertible_218i__1667275702_380062e8_progressive_thumbnail',
            'https://media.karousell.com/media/photos/products/2022/11/1/bmw_2_series_convertible_218i__1667275702_81919639_progressive',
            'https://media.karousell.com/media/photos/products/2022/11/1/bmw_2_series_convertible_218i__1667275702_a9106dfc_progressive',
        ],
        'car5' => [
            'https://media.karousell.com/media/photos/products/2022/10/12/084829_1189351703_thumbnail_progressive_thumbnail.jpg',
            'https://media.karousell.com/media/photos/products/2022/10/12/mercedes_benz_cla180_sb_urban_r18_led_1665535710_62eb8194_progressive.jpg',
            'https://media.karousell.com/media/photos/products/2022/10/12/mercedes_benz_cla180_sb_urban_r18_led_1665535710_e7e0cbc0_progressive.jpg',
        ],

    ],

    'exploreCars' => [
        'https://media.karousell.com/media/photos/special-collections/2022/10/15/autos_garage-redesign_spc-m_(1500,_610).png',
        'https://media.karousell.com/media/photos/special-collections/2022/02/23/sg_petrolupdates_m_(1500,_610).png',
    ],

    'topicSearch' => [
        'Used Car By Brands',
        'Popular Used Car Models',
        'Vehicle Rental in Singapore',
        'Popular Pages',
        'Useful Information',
        'Popular on Carousell',
    ]
];
